### PR TITLE
Change baseUrl to production instance

### PR DESCRIPTION
**Pull request by Deseao**
I have no idea how to bump the version number.

### CODE REVIEW

**Comment by kmackatvail** [comment]
Looks good

**Comment by Deseao** [comment]
@kmackatvail Are you able to run the unit tests / check if it compiles? I can't on my mac because it needs a VS library.

**Comment by kmackatvail** [comment]
@Deseao I should be able to run it on my window desktop back in DF as it has VS available.

**Comment by kmackatvail** [comment]
Used VS Professional 2017 v15.9.14

1>------ Rebuild All started: Project: persy-cs-sdk, Configuration: Release Any CPU ------
1>  persy-cs-sdk -> C:\Users\kmack\Desktop\csharp-sdk-master\persy-cs-sdk\bin\Release\persy-cs-sdk.dll
2>------ Rebuild All started: Project: persy-cs-sdk-test, Configuration: Release Any CPU ------
2>  persy-cs-sdk-test -> C:\Users\kmack\Desktop\csharp-sdk-master\persy-cs-sdk-test\bin\Release\persy-cs-sdk-test.dll
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

1>------ Rebuild All started: Project: persy-cs-sdk, Configuration: Release Any CPU ------
1>  persy-cs-sdk -> C:\Users\kmack\Desktop\csharp-sdk-master\persy-cs-sdk\bin\Release\persy-cs-sdk.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

[8/23/2019 12:36:39 PM Informational] ------ Discover test started ------
[8/23/2019 12:36:44 PM Informational] ========== Discover test finished: 163 found (0:00:05.247387) ==========
[8/23/2019 12:36:54 PM Informational] ------ Discover test started ------
[8/23/2019 12:36:54 PM Informational] ========== Discover test finished: 0 found (0:00:00.4361828) ==========
[8/23/2019 12:37:06 PM Informational] ------ Discover test started ------
[8/23/2019 12:37:07 PM Informational] ========== Discover test finished: 163 found (0:00:01.3708224) ==========
[8/23/2019 12:37:32 PM Informational] ------ Discover test started ------
[8/23/2019 12:37:32 PM Informational] ========== Discover test finished: 0 found (0:00:00.4268591) ==========
[8/23/2019 12:37:45 PM Informational] ------ Discover test started ------
[8/23/2019 12:37:47 PM Informational] ========== Discover test finished: 163 found (0:00:01.4322292) ==========
[8/23/2019 12:37:47 PM Informational] ------ Run test started ------
[8/23/2019 12:37:50 PM Informational] ========== Run test finished: 163 run (0:00:03.2607891) ==========

All tests passed

**Comment by Deseao** [comment]
Great, merging

**Pull request merged**
